name: movie_radar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.2.1+1
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  get_it: ^7.2.0
  go_router: ^7.1.1
  http: ^0.13.5
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/
  output_path: lib/presentation/app/constants/
  filename: assets.dart

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/

flutter_intl:
  enabled: true
  arb_dir: assets/lang
  output_dir: lib/presentation/app/lang
